AWSTemplateFormatVersion: '2010-09-09'
Description: fastq2fasta - SAM app that converts a FASTQ S3 file objects into FASTA
  and QUAL files.
Resources:
  ConvertFastq2Fasta:
    Properties:
      CodeUri: s3://iaqportal/c9700516ddc4b4b5f90819fedd9b203d
      Description: converts a FASTQ S3 file objects into FASTA and QUAL files and
        stores the new files in the output bucket.
      Environment:
        Variables:
          OUTPUT_BUCKET:
            Ref: OutputBucket
      Events:
        BucketEvent1:
          Properties:
            Bucket:
              Ref: SourceFastqBucket
            Events:
            - s3:ObjectCreated:*
          Type: S3
      Handler: src/app.lambda_handler
      MemorySize: 512
      Policies:
      - Statement:
        - Action:
          - s3:GetObject
          - s3:GetObjectAcl
          - s3:PutObject
          Effect: Allow
          Resource: arn:aws:s3:::*
        Version: '2012-10-17'
      Runtime: python3.6
      Timeout: 30
    Type: AWS::Serverless::Function
  OutputBucket:
    Type: AWS::S3::Bucket
  SourceFastqBucket:
    Type: AWS::S3::Bucket
Transform: AWS::Serverless-2016-10-31
