AWSTemplateFormatVersion: '2010-09-09'
Description: fastq2fasta - SAM app that converts a FASTQ S3 file objects into FASTA
  and QUAL files.
Parameters:
  OutputBucket:
    Description: Name of the S3 Bucket to put FASTA and QUAL files into (must exist
      prior to deployment)
    Type: String
  SourceFastqBucket:
    Description: Name of the S3 Bucket to read FASTQ files from (must NOT exist prior
      to deployment)
    Type: String
Resources:
  FastqConvertFunction:
    Properties:
      CodeUri: s3://iaqportal/79a1a0a33571774dda8ec763ba9c2584
      Description: converts a FASTQ S3 file objects into FASTA and QUAL files and
        stores the new files in the output bucket.
      Environment:
        Variables:
          OUTPUT_BUCKET:
            Ref: OutputBucket
      Events:
        upload:
          Properties:
            Bucket:
              Ref: SourceBucket
            Events: s3:ObjectCreated:*
          Type: S3
      Handler: src/app.lambda_handler
      Layers:
      - arn:aws:lambda:us-west-1:892335585962:layer:biopython:1
      MemorySize: 512
      Policies:
      - S3ReadPolicy:
          BucketName:
            Ref: SourceFastqBucket
      - S3CrudPolicy:
          BucketName:
            Ref: OutputBucket
      Runtime: python3.6
      Timeout: 30
    Type: AWS::Serverless::Function
  SourceBucket:
    Properties:
      BucketName:
        Ref: SourceFastqBucket
    Type: AWS::S3::Bucket
Transform: AWS::Serverless-2016-10-31
