AWSTemplateFormatVersion: '2010-09-09'
Description: fastq2fasta - SAM app that converts a FASTQ S3 Objects into FASTA and
  QUAL files (and stores labels in DynamoDB).
Resources:
  ConvertFastq2Fasta:
    Properties:
      CodeUri: s3://iaqportal/976afacfccf8b25c90ff54b9f42a9cad
      Description: converts a FASTQ S3 Objects into FASTA and QUAL files and stores
        the new files in the output bucket.
      Environment:
        Variables:
          TABLE_NAME:
            Ref: ResultsTable
      Events:
        BucketEvent1:
          Properties:
            Bucket:
              Ref: SourceFastqBucket
            Events:
            - s3:ObjectCreated:*
          Type: S3
      Handler: src/app.lambda_handler
      MemorySize: 512
      Policies:
      - Statement:
        - Action:
          - s3:GetObject
          - s3:GetObjectAcl
          - s3:PutObject
          Effect: Allow
          Resource: arn:aws:s3:::*
        - Action:
          - dynamodb:GetItem
          - dynamodb:PutItem
          - dynamodb:Scan
          - dynamodb:UpdateItem
          Effect: Allow
          Resource:
            Fn::Join:
            - ''
            - - 'arn:aws:dynamodb:'
              - Ref: AWS::Region
              - ':'
              - Ref: AWS::AccountId
              - :table/
              - Ref: ResultsTable
        Version: '2012-10-17'
      Runtime: python3.6
      Timeout: 30
    Type: AWS::Serverless::Function
  ResultsTable:
    Type: AWS::Serverless::SimpleTable
  SourceFastqBucket:
    Type: AWS::S3::Bucket
Transform: AWS::Serverless-2016-10-31
